[pytest]
# 1. Указываем Питону корень проекта, чтобы он видел папку pages
pythonpath = .

# 2. Говорим Pytest, где именно лежат тесты (чтобы он не искал их в других папках)
testpaths = tests

# 3. Базовые настройки запуска:
# -v: подробный вывод (verbose)
# -s: разрешить вывод текста (print) в терминал
# --alluredir=allure-results: всегда автоматически собирать данные для Allure-отчета
addopts = -v -s --alluredir=allure-results