name: UI Tests Pipeline

# 1. КОГДА запускать тесты?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. ГДЕ запускать и ЧТО делать?
jobs:
  test:
    # Выделяем бесплатный сервер на Linux (Ubuntu)
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Робот скачивает ваш код из GitHub к себе на сервер
    - name: Cкачивание кода
      uses: actions/checkout@v4

    # Шаг 2: Устанавливаем Python 3.11
    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Шаг 3: Устанавливаем Pytest, Playwright и Allure
    - name: Установка библиотек
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-playwright allure-pytest

    # Шаг 4: Самый важный для Playwright! Качаем сам браузер Chromium
    - name: Установка браузеров
      run: playwright install --with-deps chromium

    # Шаг 5: Запускаем наши тесты!
    - name: Запуск автотестов
      run: pytest